// AUTO-GENERATED by scripts/sync-tokens.js — DO NOT EDIT MANUALLY
// Last synced: 2026-04-05T14:53:40.007Z

export default {
  "colors": {
    "tdc-primary": "#2C2C2C",
    "tdc-dark": "#3A3A3A",
    "tdc-bg": "#F0F5F0",
    "tdc-gold": "#C1B167",
    "tdc-light": "#F5F5F5",
    "tdc-border": "#D4D4D4",
    "tdc-disabled": "#E7E7E7"
  },
  "spacing": {
    "1": "8px",
    "2": "16px",
    "3": "24px",
    "4": "32px",
    "6": "48px",
    "8": "64px",
    "10": "80px",
    "12": "96px",
    "15": "120px",
    "20": "160px"
  },
  "fontSize": {
    "display": [
      "64px",
      {
        "lineHeight": "1.1",
        "fontWeight": "700"
      }
    ],
    "h1": [
      "48px",
      {
        "lineHeight": "1.15",
        "fontWeight": "700"
      }
    ],
    "h2": [
      "32px",
      {
        "lineHeight": "1.25",
        "fontWeight": "600"
      }
    ],
    "h3": [
      "24px",
      {
        "lineHeight": "1.3",
        "fontWeight": "600"
      }
    ],
    "body": [
      "16px",
      {
        "lineHeight": "1.6",
        "fontWeight": "400"
      }
    ],
    "small": [
      "14px",
      {
        "lineHeight": "1.5",
        "fontWeight": "400"
      }
    ],
    "xs": [
      "12px",
      {
        "lineHeight": "1.4",
        "fontWeight": "400"
      }
    ]
  }
};
