/**
 * sync-tokens.js — Brand Tokens → tailwind.tokens.js
 *
 * Usage:
 *   node scripts/sync-tokens.js               ← writes tailwind.tokens.js
 *   node scripts/sync-tokens.js --check        ← dry run, reports drift only
 *
 * Optional: export tokens.json from Figma Tokens Plugin → drop in repo root.
 * Without it, writes the brand baseline directly.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_FILE = join(__dirname, '../tokens.json');
const OUTPUT_FILE = join(__dirname, '../tailwind.tokens.js');
const CHECK_ONLY = process.argv.includes('--check');

// ─── Brand baseline (source of truth) ─────────────────────────────────────
const BRAND_BASELINE = {
  colors: {
    'tdc-primary':  '#2C2C2C',
    'tdc-dark':     '#3A3A3A',
    'tdc-bg':       '#F0F5F0',
    'tdc-gold':     '#C1B167',
    'tdc-light':    '#F5F5F5',
    'tdc-border':   '#D4D4D4',
    'tdc-disabled': '#E7E7E7',
  },
  spacing: {
    '1':  '8px',
    '2':  '16px',
    '3':  '24px',
    '4':  '32px',
    '6':  '48px',
    '8':  '64px',
    '10': '80px',
    '12': '96px',
    '15': '120px',
    '20': '160px',
  },
  fontSize: {
    'display': ['64px', { lineHeight: '1.1',  fontWeight: '700' }],
    'h1':      ['48px', { lineHeight: '1.15', fontWeight: '700' }],
    'h2':      ['32px', { lineHeight: '1.25', fontWeight: '600' }],
    'h3':      ['24px', { lineHeight: '1.3',  fontWeight: '600' }],
    'body':    ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
    'small':   ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
    'xs':      ['12px', { lineHeight: '1.4',  fontWeight: '400' }],
  },
};

// ─── Drift check ──────────────────────────────────────────────────────────
function diffTokens(baseline, incoming) {
  const changes = [];
  for (const section of ['colors', 'spacing', 'fontSize']) {
    const base = baseline[section] || {};
    const next = incoming[section] || {};
    for (const key of new Set([...Object.keys(base), ...Object.keys(next)])) {
      if (JSON.stringify(base[key]) !== JSON.stringify(next[key])) {
        changes.push({ section, key, from: base[key], to: next[key] });
      }
    }
  }
  return changes;
}

// ─── Main ─────────────────────────────────────────────────────────────────
let tokens = { ...BRAND_BASELINE };

if (existsSync(TOKENS_FILE)) {
  try {
    const raw = JSON.parse(readFileSync(TOKENS_FILE, 'utf8'));
    const global = raw.global || raw;
    const parsed = { colors: {}, spacing: {}, fontSize: {} };

    if (global.color) {
      for (const [k, v] of Object.entries(global.color)) {
        if (v.value) parsed.colors[`tdc-${k}`] = v.value;
      }
    }
    if (global.spacing) {
      for (const [k, v] of Object.entries(global.spacing)) {
        if (v.value) parsed.spacing[k] = `${v.value}px`;
      }
    }

    const drift = diffTokens(BRAND_BASELINE, parsed);
    if (drift.length > 0) {
      console.log(`⚠  ${drift.length} token(s) differ from brand baseline:`);
      drift.forEach(d => console.log(`   [${d.section}] ${d.key}: ${JSON.stringify(d.from)} → ${JSON.stringify(d.to)}`));
    } else {
      console.log('✓ tokens match brand baseline');
    }
    tokens = { ...BRAND_BASELINE, ...parsed };
  } catch (e) {
    console.error('✗ Failed to parse tokens.json:', e.message);
  }
} else {
  console.log('ℹ  No tokens.json found — writing brand baseline');
}

if (CHECK_ONLY) {
  console.log('--check: no files written');
  process.exit(0);
}

const output = `// AUTO-GENERATED by scripts/sync-tokens.js — DO NOT EDIT MANUALLY
// Last synced: ${new Date().toISOString()}

export default ${JSON.stringify(tokens, null, 2)};
`;

writeFileSync(OUTPUT_FILE, output, 'utf8');
console.log('✓ tailwind.tokens.js written');
